// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersGenerateImageAiRequest(t *testing.T) {
	t.Run("SetPrompt", func(t *testing.T) {
		obj := &GenerateImageAiRequest{}
		var fernTestValuePrompt string
		obj.SetPrompt(fernTestValuePrompt)
		assert.Equal(t, fernTestValuePrompt, obj.Prompt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetModelKey", func(t *testing.T) {
		obj := &GenerateImageAiRequest{}
		var fernTestValueModelKey *GenerateImageAiRequestModelKey
		obj.SetModelKey(fernTestValueModelKey)
		assert.Equal(t, fernTestValueModelKey, obj.ModelKey)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWidth", func(t *testing.T) {
		obj := &GenerateImageAiRequest{}
		var fernTestValueWidth *int
		obj.SetWidth(fernTestValueWidth)
		assert.Equal(t, fernTestValueWidth, obj.Width)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHeight", func(t *testing.T) {
		obj := &GenerateImageAiRequest{}
		var fernTestValueHeight *int
		obj.SetHeight(fernTestValueHeight)
		assert.Equal(t, fernTestValueHeight, obj.Height)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGenerateImageAiRequest(t *testing.T) {
	t.Run("SetPrompt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GenerateImageAiRequest{}
		var fernTestValuePrompt string

		// Act
		obj.SetPrompt(fernTestValuePrompt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetModelKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GenerateImageAiRequest{}
		var fernTestValueModelKey *GenerateImageAiRequestModelKey

		// Act
		obj.SetModelKey(fernTestValueModelKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWidth_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GenerateImageAiRequest{}
		var fernTestValueWidth *int

		// Act
		obj.SetWidth(fernTestValueWidth)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHeight_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GenerateImageAiRequest{}
		var fernTestValueHeight *int

		// Act
		obj.SetHeight(fernTestValueHeight)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetGenerationAiRequest(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &GetGenerationAiRequest{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetGenerationAiRequest(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetGenerationAiRequest{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestEnumGenerateImageAiRequestModelKey(t *testing.T) {
	t.Run("NewFromString_flux_schnell", func(t *testing.T) {
		t.Parallel()
		val, err := NewGenerateImageAiRequestModelKeyFromString("flux_schnell")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, GenerateImageAiRequestModelKey("flux_schnell"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_flux_dev", func(t *testing.T) {
		t.Parallel()
		val, err := NewGenerateImageAiRequestModelKeyFromString("flux_dev")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, GenerateImageAiRequestModelKey("flux_dev"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_flux_pro_ultra", func(t *testing.T) {
		t.Parallel()
		val, err := NewGenerateImageAiRequestModelKeyFromString("flux_pro_ultra")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, GenerateImageAiRequestModelKey("flux_pro_ultra"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewGenerateImageAiRequestModelKeyFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewGenerateImageAiRequestModelKeyFromString("flux_schnell")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}
