// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/schedulin/schedulin-go/internal"
	big "math/big"
	time "time"
)

var (
	createPresignedPostFieldContentType = big.NewInt(1 << 0)
	createPresignedPostFieldKey         = big.NewInt(1 << 1)
	createPresignedPostFieldSize        = big.NewInt(1 << 2)
)

type CreatePresignedPost struct {
	ContentType string `json:"contentType" url:"-"`
	Key         string `json:"key" url:"-"`
	Size        *int   `json:"size,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreatePresignedPost) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetContentType sets the ContentType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePresignedPost) SetContentType(contentType string) {
	c.ContentType = contentType
	c.require(createPresignedPostFieldContentType)
}

// SetKey sets the Key field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePresignedPost) SetKey(key string) {
	c.Key = key
	c.require(createPresignedPostFieldKey)
}

// SetSize sets the Size field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreatePresignedPost) SetSize(size *int) {
	c.Size = size
	c.require(createPresignedPostFieldSize)
}

func (c *CreatePresignedPost) UnmarshalJSON(data []byte) error {
	type unmarshaler CreatePresignedPost
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreatePresignedPost(body)
	return nil
}

func (c *CreatePresignedPost) MarshalJSON() ([]byte, error) {
	type embed CreatePresignedPost
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	listMediaRequestFieldCursor  = big.NewInt(1 << 0)
	listMediaRequestFieldLimit   = big.NewInt(1 << 1)
	listMediaRequestFieldQ       = big.NewInt(1 << 2)
	listMediaRequestFieldType    = big.NewInt(1 << 3)
	listMediaRequestFieldTagIDs  = big.NewInt(1 << 4)
	listMediaRequestFieldTagMode = big.NewInt(1 << 5)
)

type ListMediaRequest struct {
	Cursor  *ListMediaRequestCursor  `json:"-" url:"cursor,omitempty"`
	Limit   *float64                 `json:"-" url:"limit,omitempty"`
	Q       *string                  `json:"-" url:"q,omitempty"`
	Type    *ListMediaRequestType    `json:"-" url:"type,omitempty"`
	TagIDs  []*string                `json:"-" url:"tagIds,omitempty"`
	TagMode *ListMediaRequestTagMode `json:"-" url:"tagMode,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListMediaRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMediaRequest) SetCursor(cursor *ListMediaRequestCursor) {
	l.Cursor = cursor
	l.require(listMediaRequestFieldCursor)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMediaRequest) SetLimit(limit *float64) {
	l.Limit = limit
	l.require(listMediaRequestFieldLimit)
}

// SetQ sets the Q field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMediaRequest) SetQ(q *string) {
	l.Q = q
	l.require(listMediaRequestFieldQ)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMediaRequest) SetType(type_ *ListMediaRequestType) {
	l.Type = type_
	l.require(listMediaRequestFieldType)
}

// SetTagIDs sets the TagIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMediaRequest) SetTagIDs(tagIDs []*string) {
	l.TagIDs = tagIDs
	l.require(listMediaRequestFieldTagIDs)
}

// SetTagMode sets the TagMode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMediaRequest) SetTagMode(tagMode *ListMediaRequestTagMode) {
	l.TagMode = tagMode
	l.require(listMediaRequestFieldTagMode)
}

var (
	retrieveMediaRequestFieldID = big.NewInt(1 << 0)
)

type RetrieveMediaRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RetrieveMediaRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveMediaRequest) SetID(id string) {
	r.ID = id
	r.require(retrieveMediaRequestFieldID)
}

var (
	setTagsMediaRequestFieldMediaID = big.NewInt(1 << 0)
	setTagsMediaRequestFieldTagIDs  = big.NewInt(1 << 1)
)

type SetTagsMediaRequest struct {
	MediaID string   `json:"-" url:"-"`
	TagIDs  []string `json:"tagIds" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SetTagsMediaRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetMediaID sets the MediaID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SetTagsMediaRequest) SetMediaID(mediaID string) {
	s.MediaID = mediaID
	s.require(setTagsMediaRequestFieldMediaID)
}

// SetTagIDs sets the TagIDs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SetTagsMediaRequest) SetTagIDs(tagIDs []string) {
	s.TagIDs = tagIDs
	s.require(setTagsMediaRequestFieldTagIDs)
}

func (s *SetTagsMediaRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler SetTagsMediaRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*s = SetTagsMediaRequest(body)
	return nil
}

func (s *SetTagsMediaRequest) MarshalJSON() ([]byte, error) {
	type embed SetTagsMediaRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	mediaFieldID        = big.NewInt(1 << 0)
	mediaFieldURL       = big.NewInt(1 << 1)
	mediaFieldName      = big.NewInt(1 << 2)
	mediaFieldMimeType  = big.NewInt(1 << 3)
	mediaFieldWidth     = big.NewInt(1 << 4)
	mediaFieldHeight    = big.NewInt(1 << 5)
	mediaFieldDuration  = big.NewInt(1 << 6)
	mediaFieldCreatedAt = big.NewInt(1 << 7)
	mediaFieldUpdatedAt = big.NewInt(1 << 8)
	mediaFieldUserID    = big.NewInt(1 << 9)
	mediaFieldBucket    = big.NewInt(1 << 10)
	mediaFieldKey       = big.NewInt(1 << 11)
	mediaFieldSize      = big.NewInt(1 << 12)
)

type Media struct {
	ID        string    `json:"id" url:"id"`
	URL       string    `json:"url" url:"url"`
	Name      string    `json:"name" url:"name"`
	MimeType  string    `json:"mimeType" url:"mimeType"`
	Width     *float64  `json:"width,omitempty" url:"width,omitempty"`
	Height    *float64  `json:"height,omitempty" url:"height,omitempty"`
	Duration  *float64  `json:"duration,omitempty" url:"duration,omitempty"`
	CreatedAt time.Time `json:"createdAt" url:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt" url:"updatedAt"`
	UserID    string    `json:"userId" url:"userId"`
	Bucket    string    `json:"bucket" url:"bucket"`
	Key       string    `json:"key" url:"key"`
	Size      *float64  `json:"size,omitempty" url:"size,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *Media) GetID() string {
	if m == nil {
		return ""
	}
	return m.ID
}

func (m *Media) GetURL() string {
	if m == nil {
		return ""
	}
	return m.URL
}

func (m *Media) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

func (m *Media) GetMimeType() string {
	if m == nil {
		return ""
	}
	return m.MimeType
}

func (m *Media) GetWidth() *float64 {
	if m == nil {
		return nil
	}
	return m.Width
}

func (m *Media) GetHeight() *float64 {
	if m == nil {
		return nil
	}
	return m.Height
}

func (m *Media) GetDuration() *float64 {
	if m == nil {
		return nil
	}
	return m.Duration
}

func (m *Media) GetCreatedAt() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.CreatedAt
}

func (m *Media) GetUpdatedAt() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.UpdatedAt
}

func (m *Media) GetUserID() string {
	if m == nil {
		return ""
	}
	return m.UserID
}

func (m *Media) GetBucket() string {
	if m == nil {
		return ""
	}
	return m.Bucket
}

func (m *Media) GetKey() string {
	if m == nil {
		return ""
	}
	return m.Key
}

func (m *Media) GetSize() *float64 {
	if m == nil {
		return nil
	}
	return m.Size
}

func (m *Media) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *Media) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Media) SetID(id string) {
	m.ID = id
	m.require(mediaFieldID)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Media) SetURL(url string) {
	m.URL = url
	m.require(mediaFieldURL)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Media) SetName(name string) {
	m.Name = name
	m.require(mediaFieldName)
}

// SetMimeType sets the MimeType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Media) SetMimeType(mimeType string) {
	m.MimeType = mimeType
	m.require(mediaFieldMimeType)
}

// SetWidth sets the Width field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Media) SetWidth(width *float64) {
	m.Width = width
	m.require(mediaFieldWidth)
}

// SetHeight sets the Height field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Media) SetHeight(height *float64) {
	m.Height = height
	m.require(mediaFieldHeight)
}

// SetDuration sets the Duration field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Media) SetDuration(duration *float64) {
	m.Duration = duration
	m.require(mediaFieldDuration)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Media) SetCreatedAt(createdAt time.Time) {
	m.CreatedAt = createdAt
	m.require(mediaFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Media) SetUpdatedAt(updatedAt time.Time) {
	m.UpdatedAt = updatedAt
	m.require(mediaFieldUpdatedAt)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Media) SetUserID(userID string) {
	m.UserID = userID
	m.require(mediaFieldUserID)
}

// SetBucket sets the Bucket field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Media) SetBucket(bucket string) {
	m.Bucket = bucket
	m.require(mediaFieldBucket)
}

// SetKey sets the Key field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Media) SetKey(key string) {
	m.Key = key
	m.require(mediaFieldKey)
}

// SetSize sets the Size field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *Media) SetSize(size *float64) {
	m.Size = size
	m.require(mediaFieldSize)
}

func (m *Media) UnmarshalJSON(data []byte) error {
	type embed Media
	var unmarshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed: embed(*m),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*m = Media(unmarshaler.embed)
	m.CreatedAt = unmarshaler.CreatedAt.Time()
	m.UpdatedAt = unmarshaler.UpdatedAt.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *Media) MarshalJSON() ([]byte, error) {
	type embed Media
	var marshaler = struct {
		embed
		CreatedAt *internal.DateTime `json:"createdAt"`
		UpdatedAt *internal.DateTime `json:"updatedAt"`
	}{
		embed:     embed(*m),
		CreatedAt: internal.NewDateTime(m.CreatedAt),
		UpdatedAt: internal.NewDateTime(m.UpdatedAt),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *Media) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	presignedPostFieldURL    = big.NewInt(1 << 0)
	presignedPostFieldFields = big.NewInt(1 << 1)
)

type PresignedPost struct {
	URL    string            `json:"url" url:"url"`
	Fields map[string]string `json:"fields" url:"fields"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PresignedPost) GetURL() string {
	if p == nil {
		return ""
	}
	return p.URL
}

func (p *PresignedPost) GetFields() map[string]string {
	if p == nil {
		return nil
	}
	return p.Fields
}

func (p *PresignedPost) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PresignedPost) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PresignedPost) SetURL(url string) {
	p.URL = url
	p.require(presignedPostFieldURL)
}

// SetFields sets the Fields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PresignedPost) SetFields(fields map[string]string) {
	p.Fields = fields
	p.require(presignedPostFieldFields)
}

func (p *PresignedPost) UnmarshalJSON(data []byte) error {
	type unmarshaler PresignedPost
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PresignedPost(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PresignedPost) MarshalJSON() ([]byte, error) {
	type embed PresignedPost
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PresignedPost) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	listMediaRequestCursorFieldID        = big.NewInt(1 << 0)
	listMediaRequestCursorFieldUpdatedAt = big.NewInt(1 << 1)
)

type ListMediaRequestCursor struct {
	ID        string                           `json:"id" url:"id"`
	UpdatedAt *ListMediaRequestCursorUpdatedAt `json:"updatedAt" url:"updatedAt"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListMediaRequestCursor) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListMediaRequestCursor) GetUpdatedAt() *ListMediaRequestCursorUpdatedAt {
	if l == nil {
		return nil
	}
	return l.UpdatedAt
}

func (l *ListMediaRequestCursor) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListMediaRequestCursor) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMediaRequestCursor) SetID(id string) {
	l.ID = id
	l.require(listMediaRequestCursorFieldID)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListMediaRequestCursor) SetUpdatedAt(updatedAt *ListMediaRequestCursorUpdatedAt) {
	l.UpdatedAt = updatedAt
	l.require(listMediaRequestCursorFieldUpdatedAt)
}

func (l *ListMediaRequestCursor) UnmarshalJSON(data []byte) error {
	type unmarshaler ListMediaRequestCursor
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListMediaRequestCursor(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListMediaRequestCursor) MarshalJSON() ([]byte, error) {
	type embed ListMediaRequestCursor
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListMediaRequestCursor) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

type ListMediaRequestCursorUpdatedAt struct {
	DateTime time.Time
	String   string

	typ string
}

func (l *ListMediaRequestCursorUpdatedAt) GetDateTime() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.DateTime
}

func (l *ListMediaRequestCursorUpdatedAt) GetString() string {
	if l == nil {
		return ""
	}
	return l.String
}

func (l *ListMediaRequestCursorUpdatedAt) UnmarshalJSON(data []byte) error {
	var valueDateTime *internal.DateTime
	if err := json.Unmarshal(data, &valueDateTime); err == nil {
		l.typ = "DateTime"
		l.DateTime = valueDateTime.Time()
		return nil
	}
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		l.typ = "String"
		l.String = valueString
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, l)
}

func (l ListMediaRequestCursorUpdatedAt) MarshalJSON() ([]byte, error) {
	if l.typ == "DateTime" || !l.DateTime.IsZero() {
		return json.Marshal(internal.NewDateTime(l.DateTime))
	}
	if l.typ == "String" || l.String != "" {
		return json.Marshal(l.String)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", l)
}

type ListMediaRequestCursorUpdatedAtVisitor interface {
	VisitDateTime(time.Time) error
	VisitString(string) error
}

func (l *ListMediaRequestCursorUpdatedAt) Accept(visitor ListMediaRequestCursorUpdatedAtVisitor) error {
	if l.typ == "DateTime" || !l.DateTime.IsZero() {
		return visitor.VisitDateTime(l.DateTime)
	}
	if l.typ == "String" || l.String != "" {
		return visitor.VisitString(l.String)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", l)
}

type ListMediaRequestTagMode string

const (
	ListMediaRequestTagModeAny ListMediaRequestTagMode = "ANY"
	ListMediaRequestTagModeAll ListMediaRequestTagMode = "ALL"
)

func NewListMediaRequestTagModeFromString(s string) (ListMediaRequestTagMode, error) {
	switch s {
	case "ANY":
		return ListMediaRequestTagModeAny, nil
	case "ALL":
		return ListMediaRequestTagModeAll, nil
	}
	var t ListMediaRequestTagMode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListMediaRequestTagMode) Ptr() *ListMediaRequestTagMode {
	return &l
}

type ListMediaRequestType string

const (
	ListMediaRequestTypeImage ListMediaRequestType = "image"
	ListMediaRequestTypeVideo ListMediaRequestType = "video"
	ListMediaRequestTypeAll   ListMediaRequestType = "all"
)

func NewListMediaRequestTypeFromString(s string) (ListMediaRequestType, error) {
	switch s {
	case "image":
		return ListMediaRequestTypeImage, nil
	case "video":
		return ListMediaRequestTypeVideo, nil
	case "all":
		return ListMediaRequestTypeAll, nil
	}
	var t ListMediaRequestType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l ListMediaRequestType) Ptr() *ListMediaRequestType {
	return &l
}

var (
	updateMediaRequestFieldID       = big.NewInt(1 << 0)
	updateMediaRequestFieldURL      = big.NewInt(1 << 1)
	updateMediaRequestFieldMimeType = big.NewInt(1 << 2)
	updateMediaRequestFieldWidth    = big.NewInt(1 << 3)
	updateMediaRequestFieldHeight   = big.NewInt(1 << 4)
	updateMediaRequestFieldSize     = big.NewInt(1 << 5)
	updateMediaRequestFieldDuration = big.NewInt(1 << 6)
)

type UpdateMediaRequest struct {
	ID       string   `json:"-" url:"-"`
	URL      string   `json:"url" url:"-"`
	MimeType *string  `json:"mimeType,omitempty" url:"-"`
	Width    *int     `json:"width,omitempty" url:"-"`
	Height   *int     `json:"height,omitempty" url:"-"`
	Size     *int     `json:"size,omitempty" url:"-"`
	Duration *float64 `json:"duration,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateMediaRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMediaRequest) SetID(id string) {
	u.ID = id
	u.require(updateMediaRequestFieldID)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMediaRequest) SetURL(url string) {
	u.URL = url
	u.require(updateMediaRequestFieldURL)
}

// SetMimeType sets the MimeType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMediaRequest) SetMimeType(mimeType *string) {
	u.MimeType = mimeType
	u.require(updateMediaRequestFieldMimeType)
}

// SetWidth sets the Width field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMediaRequest) SetWidth(width *int) {
	u.Width = width
	u.require(updateMediaRequestFieldWidth)
}

// SetHeight sets the Height field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMediaRequest) SetHeight(height *int) {
	u.Height = height
	u.require(updateMediaRequestFieldHeight)
}

// SetSize sets the Size field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMediaRequest) SetSize(size *int) {
	u.Size = size
	u.require(updateMediaRequestFieldSize)
}

// SetDuration sets the Duration field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateMediaRequest) SetDuration(duration *float64) {
	u.Duration = duration
	u.require(updateMediaRequestFieldDuration)
}

func (u *UpdateMediaRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateMediaRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateMediaRequest(body)
	return nil
}

func (u *UpdateMediaRequest) MarshalJSON() ([]byte, error) {
	type embed UpdateMediaRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
