// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersListPlatformsResponse(t *testing.T) {
	t.Run("SetData", func(t *testing.T) {
		obj := &ListPlatformsResponse{}
		var fernTestValueData []*ListPlatformsResponseDataItem
		obj.SetData(fernTestValueData)
		assert.Equal(t, fernTestValueData, obj.Data)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersListPlatformsResponse(t *testing.T) {
	t.Run("GetData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponse{}
		var expected []*ListPlatformsResponseDataItem
		obj.Data = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetData(), "getter should return the property value")
	})

	t.Run("GetData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponse{}
		obj.Data = nil

		// Act & Assert
		assert.Nil(t, obj.GetData(), "getter should return nil when property is nil")
	})

	t.Run("GetData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetData() // Should return zero value
	})

}

func TestSettersMarkExplicitListPlatformsResponse(t *testing.T) {
	t.Run("SetData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponse{}
		var fernTestValueData []*ListPlatformsResponseDataItem

		// Act
		obj.SetData(fernTestValueData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListPlatformsResponseDataItem(t *testing.T) {
	t.Run("SetPlatform", func(t *testing.T) {
		obj := &ListPlatformsResponseDataItem{}
		var fernTestValuePlatform string
		obj.SetPlatform(fernTestValuePlatform)
		assert.Equal(t, fernTestValuePlatform, obj.Platform)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &ListPlatformsResponseDataItem{}
		var fernTestValueName string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetComingSoon", func(t *testing.T) {
		obj := &ListPlatformsResponseDataItem{}
		var fernTestValueComingSoon *bool
		obj.SetComingSoon(fernTestValueComingSoon)
		assert.Equal(t, fernTestValueComingSoon, obj.ComingSoon)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCaptionMaxLength", func(t *testing.T) {
		obj := &ListPlatformsResponseDataItem{}
		var fernTestValueCaptionMaxLength *int
		obj.SetCaptionMaxLength(fernTestValueCaptionMaxLength)
		assert.Equal(t, fernTestValueCaptionMaxLength, obj.CaptionMaxLength)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMediaRules", func(t *testing.T) {
		obj := &ListPlatformsResponseDataItem{}
		var fernTestValueMediaRules *ListPlatformsResponseDataItemMediaRules
		obj.SetMediaRules(fernTestValueMediaRules)
		assert.Equal(t, fernTestValueMediaRules, obj.MediaRules)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPlatformConfiguration", func(t *testing.T) {
		obj := &ListPlatformsResponseDataItem{}
		var fernTestValuePlatformConfiguration *ListPlatformsResponseDataItemPlatformConfiguration
		obj.SetPlatformConfiguration(fernTestValuePlatformConfiguration)
		assert.Equal(t, fernTestValuePlatformConfiguration, obj.PlatformConfiguration)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHelperEndpoints", func(t *testing.T) {
		obj := &ListPlatformsResponseDataItem{}
		var fernTestValueHelperEndpoints []*ListPlatformsResponseDataItemHelperEndpointsItem
		obj.SetHelperEndpoints(fernTestValueHelperEndpoints)
		assert.Equal(t, fernTestValueHelperEndpoints, obj.HelperEndpoints)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersListPlatformsResponseDataItem(t *testing.T) {
	t.Run("GetPlatform", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItem{}
		var expected string
		obj.Platform = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPlatform(), "getter should return the property value")
	})

	t.Run("GetPlatform_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPlatform() // Should return zero value
	})

	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItem{}
		var expected string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

	t.Run("GetComingSoon", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItem{}
		var expected *bool
		obj.ComingSoon = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetComingSoon(), "getter should return the property value")
	})

	t.Run("GetComingSoon_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItem{}
		obj.ComingSoon = nil

		// Act & Assert
		assert.Nil(t, obj.GetComingSoon(), "getter should return nil when property is nil")
	})

	t.Run("GetComingSoon_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetComingSoon() // Should return zero value
	})

	t.Run("GetCaptionMaxLength", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItem{}
		var expected *int
		obj.CaptionMaxLength = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCaptionMaxLength(), "getter should return the property value")
	})

	t.Run("GetCaptionMaxLength_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItem{}
		obj.CaptionMaxLength = nil

		// Act & Assert
		assert.Nil(t, obj.GetCaptionMaxLength(), "getter should return nil when property is nil")
	})

	t.Run("GetCaptionMaxLength_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCaptionMaxLength() // Should return zero value
	})

	t.Run("GetMediaRules", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItem{}
		var expected *ListPlatformsResponseDataItemMediaRules
		obj.MediaRules = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMediaRules(), "getter should return the property value")
	})

	t.Run("GetMediaRules_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItem{}
		obj.MediaRules = nil

		// Act & Assert
		assert.Nil(t, obj.GetMediaRules(), "getter should return nil when property is nil")
	})

	t.Run("GetMediaRules_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMediaRules() // Should return zero value
	})

	t.Run("GetPlatformConfiguration", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItem{}
		var expected *ListPlatformsResponseDataItemPlatformConfiguration
		obj.PlatformConfiguration = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPlatformConfiguration(), "getter should return the property value")
	})

	t.Run("GetPlatformConfiguration_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItem{}
		obj.PlatformConfiguration = nil

		// Act & Assert
		assert.Nil(t, obj.GetPlatformConfiguration(), "getter should return nil when property is nil")
	})

	t.Run("GetPlatformConfiguration_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPlatformConfiguration() // Should return zero value
	})

	t.Run("GetHelperEndpoints", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItem{}
		var expected []*ListPlatformsResponseDataItemHelperEndpointsItem
		obj.HelperEndpoints = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHelperEndpoints(), "getter should return the property value")
	})

	t.Run("GetHelperEndpoints_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItem{}
		obj.HelperEndpoints = nil

		// Act & Assert
		assert.Nil(t, obj.GetHelperEndpoints(), "getter should return nil when property is nil")
	})

	t.Run("GetHelperEndpoints_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHelperEndpoints() // Should return zero value
	})

}

func TestSettersMarkExplicitListPlatformsResponseDataItem(t *testing.T) {
	t.Run("SetPlatform_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItem{}
		var fernTestValuePlatform string

		// Act
		obj.SetPlatform(fernTestValuePlatform)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItem{}
		var fernTestValueName string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetComingSoon_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItem{}
		var fernTestValueComingSoon *bool

		// Act
		obj.SetComingSoon(fernTestValueComingSoon)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCaptionMaxLength_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItem{}
		var fernTestValueCaptionMaxLength *int

		// Act
		obj.SetCaptionMaxLength(fernTestValueCaptionMaxLength)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMediaRules_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItem{}
		var fernTestValueMediaRules *ListPlatformsResponseDataItemMediaRules

		// Act
		obj.SetMediaRules(fernTestValueMediaRules)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPlatformConfiguration_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItem{}
		var fernTestValuePlatformConfiguration *ListPlatformsResponseDataItemPlatformConfiguration

		// Act
		obj.SetPlatformConfiguration(fernTestValuePlatformConfiguration)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHelperEndpoints_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItem{}
		var fernTestValueHelperEndpoints []*ListPlatformsResponseDataItemHelperEndpointsItem

		// Act
		obj.SetHelperEndpoints(fernTestValueHelperEndpoints)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListPlatformsResponseDataItemHelperEndpointsItem(t *testing.T) {
	t.Run("SetMethod", func(t *testing.T) {
		obj := &ListPlatformsResponseDataItemHelperEndpointsItem{}
		var fernTestValueMethod string
		obj.SetMethod(fernTestValueMethod)
		assert.Equal(t, fernTestValueMethod, obj.Method)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPath", func(t *testing.T) {
		obj := &ListPlatformsResponseDataItemHelperEndpointsItem{}
		var fernTestValuePath string
		obj.SetPath(fernTestValuePath)
		assert.Equal(t, fernTestValuePath, obj.Path)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDescription", func(t *testing.T) {
		obj := &ListPlatformsResponseDataItemHelperEndpointsItem{}
		var fernTestValueDescription string
		obj.SetDescription(fernTestValueDescription)
		assert.Equal(t, fernTestValueDescription, obj.Description)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersListPlatformsResponseDataItemHelperEndpointsItem(t *testing.T) {
	t.Run("GetMethod", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemHelperEndpointsItem{}
		var expected string
		obj.Method = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMethod(), "getter should return the property value")
	})

	t.Run("GetMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItemHelperEndpointsItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMethod() // Should return zero value
	})

	t.Run("GetPath", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemHelperEndpointsItem{}
		var expected string
		obj.Path = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPath(), "getter should return the property value")
	})

	t.Run("GetPath_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItemHelperEndpointsItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPath() // Should return zero value
	})

	t.Run("GetDescription", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemHelperEndpointsItem{}
		var expected string
		obj.Description = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDescription(), "getter should return the property value")
	})

	t.Run("GetDescription_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItemHelperEndpointsItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDescription() // Should return zero value
	})

}

func TestSettersMarkExplicitListPlatformsResponseDataItemHelperEndpointsItem(t *testing.T) {
	t.Run("SetMethod_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemHelperEndpointsItem{}
		var fernTestValueMethod string

		// Act
		obj.SetMethod(fernTestValueMethod)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPath_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemHelperEndpointsItem{}
		var fernTestValuePath string

		// Act
		obj.SetPath(fernTestValuePath)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDescription_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemHelperEndpointsItem{}
		var fernTestValueDescription string

		// Act
		obj.SetDescription(fernTestValueDescription)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListPlatformsResponseDataItemMediaRules(t *testing.T) {
	t.Run("SetMin", func(t *testing.T) {
		obj := &ListPlatformsResponseDataItemMediaRules{}
		var fernTestValueMin *int
		obj.SetMin(fernTestValueMin)
		assert.Equal(t, fernTestValueMin, obj.Min)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMax", func(t *testing.T) {
		obj := &ListPlatformsResponseDataItemMediaRules{}
		var fernTestValueMax int
		obj.SetMax(fernTestValueMax)
		assert.Equal(t, fernTestValueMax, obj.Max)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAllowedTypes", func(t *testing.T) {
		obj := &ListPlatformsResponseDataItemMediaRules{}
		var fernTestValueAllowedTypes []ListPlatformsResponseDataItemMediaRulesAllowedTypesItem
		obj.SetAllowedTypes(fernTestValueAllowedTypes)
		assert.Equal(t, fernTestValueAllowedTypes, obj.AllowedTypes)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAllowedDimensions", func(t *testing.T) {
		obj := &ListPlatformsResponseDataItemMediaRules{}
		var fernTestValueAllowedDimensions []*ListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem
		obj.SetAllowedDimensions(fernTestValueAllowedDimensions)
		assert.Equal(t, fernTestValueAllowedDimensions, obj.AllowedDimensions)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersListPlatformsResponseDataItemMediaRules(t *testing.T) {
	t.Run("GetMin", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemMediaRules{}
		var expected *int
		obj.Min = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMin(), "getter should return the property value")
	})

	t.Run("GetMin_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemMediaRules{}
		obj.Min = nil

		// Act & Assert
		assert.Nil(t, obj.GetMin(), "getter should return nil when property is nil")
	})

	t.Run("GetMin_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItemMediaRules
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMin() // Should return zero value
	})

	t.Run("GetMax", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemMediaRules{}
		var expected int
		obj.Max = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMax(), "getter should return the property value")
	})

	t.Run("GetMax_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItemMediaRules
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMax() // Should return zero value
	})

	t.Run("GetAllowedTypes", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemMediaRules{}
		var expected []ListPlatformsResponseDataItemMediaRulesAllowedTypesItem
		obj.AllowedTypes = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAllowedTypes(), "getter should return the property value")
	})

	t.Run("GetAllowedTypes_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemMediaRules{}
		obj.AllowedTypes = nil

		// Act & Assert
		assert.Nil(t, obj.GetAllowedTypes(), "getter should return nil when property is nil")
	})

	t.Run("GetAllowedTypes_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItemMediaRules
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAllowedTypes() // Should return zero value
	})

	t.Run("GetAllowedDimensions", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemMediaRules{}
		var expected []*ListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem
		obj.AllowedDimensions = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAllowedDimensions(), "getter should return the property value")
	})

	t.Run("GetAllowedDimensions_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemMediaRules{}
		obj.AllowedDimensions = nil

		// Act & Assert
		assert.Nil(t, obj.GetAllowedDimensions(), "getter should return nil when property is nil")
	})

	t.Run("GetAllowedDimensions_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItemMediaRules
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAllowedDimensions() // Should return zero value
	})

}

func TestSettersMarkExplicitListPlatformsResponseDataItemMediaRules(t *testing.T) {
	t.Run("SetMin_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemMediaRules{}
		var fernTestValueMin *int

		// Act
		obj.SetMin(fernTestValueMin)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMax_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemMediaRules{}
		var fernTestValueMax int

		// Act
		obj.SetMax(fernTestValueMax)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAllowedTypes_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemMediaRules{}
		var fernTestValueAllowedTypes []ListPlatformsResponseDataItemMediaRulesAllowedTypesItem

		// Act
		obj.SetAllowedTypes(fernTestValueAllowedTypes)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAllowedDimensions_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemMediaRules{}
		var fernTestValueAllowedDimensions []*ListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem

		// Act
		obj.SetAllowedDimensions(fernTestValueAllowedDimensions)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem(t *testing.T) {
	t.Run("SetWidth", func(t *testing.T) {
		obj := &ListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem{}
		var fernTestValueWidth int
		obj.SetWidth(fernTestValueWidth)
		assert.Equal(t, fernTestValueWidth, obj.Width)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHeight", func(t *testing.T) {
		obj := &ListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem{}
		var fernTestValueHeight int
		obj.SetHeight(fernTestValueHeight)
		assert.Equal(t, fernTestValueHeight, obj.Height)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem(t *testing.T) {
	t.Run("GetWidth", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem{}
		var expected int
		obj.Width = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetWidth(), "getter should return the property value")
	})

	t.Run("GetWidth_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetWidth() // Should return zero value
	})

	t.Run("GetHeight", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem{}
		var expected int
		obj.Height = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHeight(), "getter should return the property value")
	})

	t.Run("GetHeight_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHeight() // Should return zero value
	})

}

func TestSettersMarkExplicitListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem(t *testing.T) {
	t.Run("SetWidth_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem{}
		var fernTestValueWidth int

		// Act
		obj.SetWidth(fernTestValueWidth)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHeight_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem{}
		var fernTestValueHeight int

		// Act
		obj.SetHeight(fernTestValueHeight)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListPlatformsResponseDataItemPlatformConfiguration(t *testing.T) {
	t.Run("SetRequired", func(t *testing.T) {
		obj := &ListPlatformsResponseDataItemPlatformConfiguration{}
		var fernTestValueRequired bool
		obj.SetRequired(fernTestValueRequired)
		assert.Equal(t, fernTestValueRequired, obj.Required)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetValidated", func(t *testing.T) {
		obj := &ListPlatformsResponseDataItemPlatformConfiguration{}
		var fernTestValueValidated bool
		obj.SetValidated(fernTestValueValidated)
		assert.Equal(t, fernTestValueValidated, obj.Validated)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSchema", func(t *testing.T) {
		obj := &ListPlatformsResponseDataItemPlatformConfiguration{}
		var fernTestValueSchema map[string]any
		obj.SetSchema(fernTestValueSchema)
		assert.Equal(t, fernTestValueSchema, obj.Schema)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersListPlatformsResponseDataItemPlatformConfiguration(t *testing.T) {
	t.Run("GetRequired", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemPlatformConfiguration{}
		var expected bool
		obj.Required = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRequired(), "getter should return the property value")
	})

	t.Run("GetRequired_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItemPlatformConfiguration
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRequired() // Should return zero value
	})

	t.Run("GetValidated", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemPlatformConfiguration{}
		var expected bool
		obj.Validated = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetValidated(), "getter should return the property value")
	})

	t.Run("GetValidated_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItemPlatformConfiguration
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetValidated() // Should return zero value
	})

	t.Run("GetSchema", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemPlatformConfiguration{}
		var expected map[string]any
		obj.Schema = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSchema(), "getter should return the property value")
	})

	t.Run("GetSchema_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemPlatformConfiguration{}
		obj.Schema = nil

		// Act & Assert
		assert.Nil(t, obj.GetSchema(), "getter should return nil when property is nil")
	})

	t.Run("GetSchema_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItemPlatformConfiguration
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSchema() // Should return zero value
	})

}

func TestSettersMarkExplicitListPlatformsResponseDataItemPlatformConfiguration(t *testing.T) {
	t.Run("SetRequired_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemPlatformConfiguration{}
		var fernTestValueRequired bool

		// Act
		obj.SetRequired(fernTestValueRequired)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetValidated_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemPlatformConfiguration{}
		var fernTestValueValidated bool

		// Act
		obj.SetValidated(fernTestValueValidated)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSchema_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemPlatformConfiguration{}
		var fernTestValueSchema map[string]any

		// Act
		obj.SetSchema(fernTestValueSchema)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingListPlatformsResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ListPlatformsResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ListPlatformsResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ListPlatformsResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingListPlatformsResponseDataItem(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItem{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ListPlatformsResponseDataItem
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ListPlatformsResponseDataItem
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ListPlatformsResponseDataItem
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingListPlatformsResponseDataItemHelperEndpointsItem(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemHelperEndpointsItem{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ListPlatformsResponseDataItemHelperEndpointsItem
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ListPlatformsResponseDataItemHelperEndpointsItem
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ListPlatformsResponseDataItemHelperEndpointsItem
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingListPlatformsResponseDataItemMediaRules(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemMediaRules{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ListPlatformsResponseDataItemMediaRules
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ListPlatformsResponseDataItemMediaRules
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ListPlatformsResponseDataItemMediaRules
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingListPlatformsResponseDataItemPlatformConfiguration(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListPlatformsResponseDataItemPlatformConfiguration{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ListPlatformsResponseDataItemPlatformConfiguration
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ListPlatformsResponseDataItemPlatformConfiguration
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ListPlatformsResponseDataItemPlatformConfiguration
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringListPlatformsResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ListPlatformsResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringListPlatformsResponseDataItem(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ListPlatformsResponseDataItem{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItem
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringListPlatformsResponseDataItemHelperEndpointsItem(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ListPlatformsResponseDataItemHelperEndpointsItem{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItemHelperEndpointsItem
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringListPlatformsResponseDataItemMediaRules(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ListPlatformsResponseDataItemMediaRules{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItemMediaRules
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringListPlatformsResponseDataItemPlatformConfiguration(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ListPlatformsResponseDataItemPlatformConfiguration{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItemPlatformConfiguration
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumListPlatformsResponseDataItemMediaRulesAllowedTypesItem(t *testing.T) {
	t.Run("NewFromString_IMAGE", func(t *testing.T) {
		t.Parallel()
		val, err := NewListPlatformsResponseDataItemMediaRulesAllowedTypesItemFromString("IMAGE")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ListPlatformsResponseDataItemMediaRulesAllowedTypesItem("IMAGE"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_VIDEO", func(t *testing.T) {
		t.Parallel()
		val, err := NewListPlatformsResponseDataItemMediaRulesAllowedTypesItemFromString("VIDEO")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ListPlatformsResponseDataItemMediaRulesAllowedTypesItem("VIDEO"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_GIF", func(t *testing.T) {
		t.Parallel()
		val, err := NewListPlatformsResponseDataItemMediaRulesAllowedTypesItemFromString("GIF")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ListPlatformsResponseDataItemMediaRulesAllowedTypesItem("GIF"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewListPlatformsResponseDataItemMediaRulesAllowedTypesItemFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewListPlatformsResponseDataItemMediaRulesAllowedTypesItemFromString("IMAGE")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesListPlatformsResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ListPlatformsResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesListPlatformsResponseDataItem(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ListPlatformsResponseDataItem{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItem
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesListPlatformsResponseDataItemHelperEndpointsItem(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ListPlatformsResponseDataItemHelperEndpointsItem{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItemHelperEndpointsItem
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesListPlatformsResponseDataItemMediaRules(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ListPlatformsResponseDataItemMediaRules{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItemMediaRules
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItemMediaRulesAllowedDimensionsItem
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesListPlatformsResponseDataItemPlatformConfiguration(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ListPlatformsResponseDataItemPlatformConfiguration{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListPlatformsResponseDataItemPlatformConfiguration
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
