// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersDeleteSocialAccountsRequest(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &DeleteSocialAccountsRequest{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitDeleteSocialAccountsRequest(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteSocialAccountsRequest{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersRefreshProfileSocialAccountsRequest(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &RefreshProfileSocialAccountsRequest{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitRefreshProfileSocialAccountsRequest(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RefreshProfileSocialAccountsRequest{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersDeleteSocialAccountsResponse(t *testing.T) {
	t.Run("SetSuccess", func(t *testing.T) {
		obj := &DeleteSocialAccountsResponse{}
		var fernTestValueSuccess bool
		obj.SetSuccess(fernTestValueSuccess)
		assert.Equal(t, fernTestValueSuccess, obj.Success)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersDeleteSocialAccountsResponse(t *testing.T) {
	t.Run("GetSuccess", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteSocialAccountsResponse{}
		var expected bool
		obj.Success = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSuccess(), "getter should return the property value")
	})

	t.Run("GetSuccess_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeleteSocialAccountsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSuccess() // Should return zero value
	})

}

func TestSettersMarkExplicitDeleteSocialAccountsResponse(t *testing.T) {
	t.Run("SetSuccess_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteSocialAccountsResponse{}
		var fernTestValueSuccess bool

		// Act
		obj.SetSuccess(fernTestValueSuccess)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersListSocialAccountsResponseItem(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &ListSocialAccountsResponseItem{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPlatform", func(t *testing.T) {
		obj := &ListSocialAccountsResponseItem{}
		var fernTestValuePlatform ListSocialAccountsResponseItemPlatform
		obj.SetPlatform(fernTestValuePlatform)
		assert.Equal(t, fernTestValuePlatform, obj.Platform)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStatus", func(t *testing.T) {
		obj := &ListSocialAccountsResponseItem{}
		var fernTestValueStatus ListSocialAccountsResponseItemStatus
		obj.SetStatus(fernTestValueStatus)
		assert.Equal(t, fernTestValueStatus, obj.Status)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUsername", func(t *testing.T) {
		obj := &ListSocialAccountsResponseItem{}
		var fernTestValueUsername *string
		obj.SetUsername(fernTestValueUsername)
		assert.Equal(t, fernTestValueUsername, obj.Username)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDisplayName", func(t *testing.T) {
		obj := &ListSocialAccountsResponseItem{}
		var fernTestValueDisplayName *string
		obj.SetDisplayName(fernTestValueDisplayName)
		assert.Equal(t, fernTestValueDisplayName, obj.DisplayName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetProfileImageURL", func(t *testing.T) {
		obj := &ListSocialAccountsResponseItem{}
		var fernTestValueProfileImageURL *string
		obj.SetProfileImageURL(fernTestValueProfileImageURL)
		assert.Equal(t, fernTestValueProfileImageURL, obj.ProfileImageURL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRefreshTokenValid", func(t *testing.T) {
		obj := &ListSocialAccountsResponseItem{}
		var fernTestValueRefreshTokenValid bool
		obj.SetRefreshTokenValid(fernTestValueRefreshTokenValid)
		assert.Equal(t, fernTestValueRefreshTokenValid, obj.RefreshTokenValid)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAnalyticsDisabledAt", func(t *testing.T) {
		obj := &ListSocialAccountsResponseItem{}
		var fernTestValueAnalyticsDisabledAt *time.Time
		obj.SetAnalyticsDisabledAt(fernTestValueAnalyticsDisabledAt)
		assert.Equal(t, fernTestValueAnalyticsDisabledAt, obj.AnalyticsDisabledAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedAt", func(t *testing.T) {
		obj := &ListSocialAccountsResponseItem{}
		var fernTestValueCreatedAt time.Time
		obj.SetCreatedAt(fernTestValueCreatedAt)
		assert.Equal(t, fernTestValueCreatedAt, obj.CreatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUpdatedAt", func(t *testing.T) {
		obj := &ListSocialAccountsResponseItem{}
		var fernTestValueUpdatedAt time.Time
		obj.SetUpdatedAt(fernTestValueUpdatedAt)
		assert.Equal(t, fernTestValueUpdatedAt, obj.UpdatedAt)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersListSocialAccountsResponseItem(t *testing.T) {
	t.Run("GetID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		var expected string
		obj.ID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetID(), "getter should return the property value")
	})

	t.Run("GetID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListSocialAccountsResponseItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetID() // Should return zero value
	})

	t.Run("GetPlatform", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		var expected ListSocialAccountsResponseItemPlatform
		obj.Platform = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPlatform(), "getter should return the property value")
	})

	t.Run("GetPlatform_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListSocialAccountsResponseItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPlatform() // Should return zero value
	})

	t.Run("GetStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		var expected ListSocialAccountsResponseItemStatus
		obj.Status = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStatus(), "getter should return the property value")
	})

	t.Run("GetStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListSocialAccountsResponseItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStatus() // Should return zero value
	})

	t.Run("GetUsername", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		var expected *string
		obj.Username = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUsername(), "getter should return the property value")
	})

	t.Run("GetUsername_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		obj.Username = nil

		// Act & Assert
		assert.Nil(t, obj.GetUsername(), "getter should return nil when property is nil")
	})

	t.Run("GetUsername_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListSocialAccountsResponseItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUsername() // Should return zero value
	})

	t.Run("GetDisplayName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		var expected *string
		obj.DisplayName = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDisplayName(), "getter should return the property value")
	})

	t.Run("GetDisplayName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		obj.DisplayName = nil

		// Act & Assert
		assert.Nil(t, obj.GetDisplayName(), "getter should return nil when property is nil")
	})

	t.Run("GetDisplayName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListSocialAccountsResponseItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDisplayName() // Should return zero value
	})

	t.Run("GetProfileImageURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		var expected *string
		obj.ProfileImageURL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetProfileImageURL(), "getter should return the property value")
	})

	t.Run("GetProfileImageURL_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		obj.ProfileImageURL = nil

		// Act & Assert
		assert.Nil(t, obj.GetProfileImageURL(), "getter should return nil when property is nil")
	})

	t.Run("GetProfileImageURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListSocialAccountsResponseItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetProfileImageURL() // Should return zero value
	})

	t.Run("GetRefreshTokenValid", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		var expected bool
		obj.RefreshTokenValid = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRefreshTokenValid(), "getter should return the property value")
	})

	t.Run("GetRefreshTokenValid_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListSocialAccountsResponseItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRefreshTokenValid() // Should return zero value
	})

	t.Run("GetAnalyticsDisabledAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		var expected *time.Time
		obj.AnalyticsDisabledAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAnalyticsDisabledAt(), "getter should return the property value")
	})

	t.Run("GetAnalyticsDisabledAt_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		obj.AnalyticsDisabledAt = nil

		// Act & Assert
		assert.Nil(t, obj.GetAnalyticsDisabledAt(), "getter should return nil when property is nil")
	})

	t.Run("GetAnalyticsDisabledAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListSocialAccountsResponseItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAnalyticsDisabledAt() // Should return zero value
	})

	t.Run("GetCreatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		var expected time.Time
		obj.CreatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedAt(), "getter should return the property value")
	})

	t.Run("GetCreatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListSocialAccountsResponseItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedAt() // Should return zero value
	})

	t.Run("GetUpdatedAt", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		var expected time.Time
		obj.UpdatedAt = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUpdatedAt(), "getter should return the property value")
	})

	t.Run("GetUpdatedAt_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListSocialAccountsResponseItem
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUpdatedAt() // Should return zero value
	})

}

func TestSettersMarkExplicitListSocialAccountsResponseItem(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPlatform_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		var fernTestValuePlatform ListSocialAccountsResponseItemPlatform

		// Act
		obj.SetPlatform(fernTestValuePlatform)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		var fernTestValueStatus ListSocialAccountsResponseItemStatus

		// Act
		obj.SetStatus(fernTestValueStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUsername_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		var fernTestValueUsername *string

		// Act
		obj.SetUsername(fernTestValueUsername)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDisplayName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		var fernTestValueDisplayName *string

		// Act
		obj.SetDisplayName(fernTestValueDisplayName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetProfileImageURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		var fernTestValueProfileImageURL *string

		// Act
		obj.SetProfileImageURL(fernTestValueProfileImageURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRefreshTokenValid_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		var fernTestValueRefreshTokenValid bool

		// Act
		obj.SetRefreshTokenValid(fernTestValueRefreshTokenValid)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAnalyticsDisabledAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		var fernTestValueAnalyticsDisabledAt *time.Time

		// Act
		obj.SetAnalyticsDisabledAt(fernTestValueAnalyticsDisabledAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		var fernTestValueCreatedAt time.Time

		// Act
		obj.SetCreatedAt(fernTestValueCreatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUpdatedAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}
		var fernTestValueUpdatedAt time.Time

		// Act
		obj.SetUpdatedAt(fernTestValueUpdatedAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersRefreshProfileSocialAccountsResponse(t *testing.T) {
	t.Run("SetSuccess", func(t *testing.T) {
		obj := &RefreshProfileSocialAccountsResponse{}
		var fernTestValueSuccess bool
		obj.SetSuccess(fernTestValueSuccess)
		assert.Equal(t, fernTestValueSuccess, obj.Success)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUsername", func(t *testing.T) {
		obj := &RefreshProfileSocialAccountsResponse{}
		var fernTestValueUsername *string
		obj.SetUsername(fernTestValueUsername)
		assert.Equal(t, fernTestValueUsername, obj.Username)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetImageURL", func(t *testing.T) {
		obj := &RefreshProfileSocialAccountsResponse{}
		var fernTestValueImageURL *string
		obj.SetImageURL(fernTestValueImageURL)
		assert.Equal(t, fernTestValueImageURL, obj.ImageURL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &RefreshProfileSocialAccountsResponse{}
		var fernTestValueName *string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersRefreshProfileSocialAccountsResponse(t *testing.T) {
	t.Run("GetSuccess", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RefreshProfileSocialAccountsResponse{}
		var expected bool
		obj.Success = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSuccess(), "getter should return the property value")
	})

	t.Run("GetSuccess_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RefreshProfileSocialAccountsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSuccess() // Should return zero value
	})

	t.Run("GetUsername", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RefreshProfileSocialAccountsResponse{}
		var expected *string
		obj.Username = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUsername(), "getter should return the property value")
	})

	t.Run("GetUsername_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RefreshProfileSocialAccountsResponse{}
		obj.Username = nil

		// Act & Assert
		assert.Nil(t, obj.GetUsername(), "getter should return nil when property is nil")
	})

	t.Run("GetUsername_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RefreshProfileSocialAccountsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUsername() // Should return zero value
	})

	t.Run("GetImageURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RefreshProfileSocialAccountsResponse{}
		var expected *string
		obj.ImageURL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetImageURL(), "getter should return the property value")
	})

	t.Run("GetImageURL_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RefreshProfileSocialAccountsResponse{}
		obj.ImageURL = nil

		// Act & Assert
		assert.Nil(t, obj.GetImageURL(), "getter should return nil when property is nil")
	})

	t.Run("GetImageURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RefreshProfileSocialAccountsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetImageURL() // Should return zero value
	})

	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RefreshProfileSocialAccountsResponse{}
		var expected *string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RefreshProfileSocialAccountsResponse{}
		obj.Name = nil

		// Act & Assert
		assert.Nil(t, obj.GetName(), "getter should return nil when property is nil")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RefreshProfileSocialAccountsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

}

func TestSettersMarkExplicitRefreshProfileSocialAccountsResponse(t *testing.T) {
	t.Run("SetSuccess_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RefreshProfileSocialAccountsResponse{}
		var fernTestValueSuccess bool

		// Act
		obj.SetSuccess(fernTestValueSuccess)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUsername_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RefreshProfileSocialAccountsResponse{}
		var fernTestValueUsername *string

		// Act
		obj.SetUsername(fernTestValueUsername)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetImageURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RefreshProfileSocialAccountsResponse{}
		var fernTestValueImageURL *string

		// Act
		obj.SetImageURL(fernTestValueImageURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RefreshProfileSocialAccountsResponse{}
		var fernTestValueName *string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersUpdateSocialAccountsResponse(t *testing.T) {
	t.Run("SetSuccess", func(t *testing.T) {
		obj := &UpdateSocialAccountsResponse{}
		var fernTestValueSuccess bool
		obj.SetSuccess(fernTestValueSuccess)
		assert.Equal(t, fernTestValueSuccess, obj.Success)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersUpdateSocialAccountsResponse(t *testing.T) {
	t.Run("GetSuccess", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSocialAccountsResponse{}
		var expected bool
		obj.Success = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSuccess(), "getter should return the property value")
	})

	t.Run("GetSuccess_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdateSocialAccountsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSuccess() // Should return zero value
	})

}

func TestSettersMarkExplicitUpdateSocialAccountsResponse(t *testing.T) {
	t.Run("SetSuccess_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSocialAccountsResponse{}
		var fernTestValueSuccess bool

		// Act
		obj.SetSuccess(fernTestValueSuccess)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersUpdateTimezoneSocialAccountsResponse(t *testing.T) {
	t.Run("SetSuccess", func(t *testing.T) {
		obj := &UpdateTimezoneSocialAccountsResponse{}
		var fernTestValueSuccess bool
		obj.SetSuccess(fernTestValueSuccess)
		assert.Equal(t, fernTestValueSuccess, obj.Success)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersUpdateTimezoneSocialAccountsResponse(t *testing.T) {
	t.Run("GetSuccess", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateTimezoneSocialAccountsResponse{}
		var expected bool
		obj.Success = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSuccess(), "getter should return the property value")
	})

	t.Run("GetSuccess_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdateTimezoneSocialAccountsResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSuccess() // Should return zero value
	})

}

func TestSettersMarkExplicitUpdateTimezoneSocialAccountsResponse(t *testing.T) {
	t.Run("SetSuccess_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateTimezoneSocialAccountsResponse{}
		var fernTestValueSuccess bool

		// Act
		obj.SetSuccess(fernTestValueSuccess)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersUpdateSocialAccountsRequest(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPlatform", func(t *testing.T) {
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValuePlatform *UpdateSocialAccountsRequestPlatform
		obj.SetPlatform(fernTestValuePlatform)
		assert.Equal(t, fernTestValuePlatform, obj.Platform)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAccessToken", func(t *testing.T) {
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValueAccessToken *string
		obj.SetAccessToken(fernTestValueAccessToken)
		assert.Equal(t, fernTestValueAccessToken, obj.AccessToken)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSecretAccessToken", func(t *testing.T) {
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValueSecretAccessToken *string
		obj.SetSecretAccessToken(fernTestValueSecretAccessToken)
		assert.Equal(t, fernTestValueSecretAccessToken, obj.SecretAccessToken)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRefreshToken", func(t *testing.T) {
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValueRefreshToken *string
		obj.SetRefreshToken(fernTestValueRefreshToken)
		assert.Equal(t, fernTestValueRefreshToken, obj.RefreshToken)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRefreshTokenValid", func(t *testing.T) {
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValueRefreshTokenValid *bool
		obj.SetRefreshTokenValid(fernTestValueRefreshTokenValid)
		assert.Equal(t, fernTestValueRefreshTokenValid, obj.RefreshTokenValid)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTokenExpiresAt", func(t *testing.T) {
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValueTokenExpiresAt *time.Time
		obj.SetTokenExpiresAt(fernTestValueTokenExpiresAt)
		assert.Equal(t, fernTestValueTokenExpiresAt, obj.TokenExpiresAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetImageURL", func(t *testing.T) {
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValueImageURL *string
		obj.SetImageURL(fernTestValueImageURL)
		assert.Equal(t, fernTestValueImageURL, obj.ImageURL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetImageProcessingStatus", func(t *testing.T) {
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValueImageProcessingStatus *UpdateSocialAccountsRequestImageProcessingStatus
		obj.SetImageProcessingStatus(fernTestValueImageProcessingStatus)
		assert.Equal(t, fernTestValueImageProcessingStatus, obj.ImageProcessingStatus)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPlatformData", func(t *testing.T) {
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValuePlatformData map[string]any
		obj.SetPlatformData(fernTestValuePlatformData)
		assert.Equal(t, fernTestValuePlatformData, obj.PlatformData)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLastRefreshAt", func(t *testing.T) {
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValueLastRefreshAt *time.Time
		obj.SetLastRefreshAt(fernTestValueLastRefreshAt)
		assert.Equal(t, fernTestValueLastRefreshAt, obj.LastRefreshAt)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStatus", func(t *testing.T) {
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValueStatus *UpdateSocialAccountsRequestStatus
		obj.SetStatus(fernTestValueStatus)
		assert.Equal(t, fernTestValueStatus, obj.Status)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitUpdateSocialAccountsRequest(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPlatform_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValuePlatform *UpdateSocialAccountsRequestPlatform

		// Act
		obj.SetPlatform(fernTestValuePlatform)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAccessToken_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValueAccessToken *string

		// Act
		obj.SetAccessToken(fernTestValueAccessToken)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSecretAccessToken_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValueSecretAccessToken *string

		// Act
		obj.SetSecretAccessToken(fernTestValueSecretAccessToken)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRefreshToken_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValueRefreshToken *string

		// Act
		obj.SetRefreshToken(fernTestValueRefreshToken)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRefreshTokenValid_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValueRefreshTokenValid *bool

		// Act
		obj.SetRefreshTokenValid(fernTestValueRefreshTokenValid)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTokenExpiresAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValueTokenExpiresAt *time.Time

		// Act
		obj.SetTokenExpiresAt(fernTestValueTokenExpiresAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetImageURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValueImageURL *string

		// Act
		obj.SetImageURL(fernTestValueImageURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetImageProcessingStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValueImageProcessingStatus *UpdateSocialAccountsRequestImageProcessingStatus

		// Act
		obj.SetImageProcessingStatus(fernTestValueImageProcessingStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPlatformData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValuePlatformData map[string]any

		// Act
		obj.SetPlatformData(fernTestValuePlatformData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLastRefreshAt_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValueLastRefreshAt *time.Time

		// Act
		obj.SetLastRefreshAt(fernTestValueLastRefreshAt)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSocialAccountsRequest{}
		var fernTestValueStatus *UpdateSocialAccountsRequestStatus

		// Act
		obj.SetStatus(fernTestValueStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersUpdateTimezoneSocialAccountsRequest(t *testing.T) {
	t.Run("SetID", func(t *testing.T) {
		obj := &UpdateTimezoneSocialAccountsRequest{}
		var fernTestValueID string
		obj.SetID(fernTestValueID)
		assert.Equal(t, fernTestValueID, obj.ID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTimezone", func(t *testing.T) {
		obj := &UpdateTimezoneSocialAccountsRequest{}
		var fernTestValueTimezone string
		obj.SetTimezone(fernTestValueTimezone)
		assert.Equal(t, fernTestValueTimezone, obj.Timezone)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitUpdateTimezoneSocialAccountsRequest(t *testing.T) {
	t.Run("SetID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateTimezoneSocialAccountsRequest{}
		var fernTestValueID string

		// Act
		obj.SetID(fernTestValueID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTimezone_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateTimezoneSocialAccountsRequest{}
		var fernTestValueTimezone string

		// Act
		obj.SetTimezone(fernTestValueTimezone)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingDeleteSocialAccountsResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeleteSocialAccountsResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled DeleteSocialAccountsResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj DeleteSocialAccountsResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj DeleteSocialAccountsResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingListSocialAccountsResponseItem(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ListSocialAccountsResponseItem{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled ListSocialAccountsResponseItem
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj ListSocialAccountsResponseItem
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj ListSocialAccountsResponseItem
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingRefreshProfileSocialAccountsResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &RefreshProfileSocialAccountsResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled RefreshProfileSocialAccountsResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj RefreshProfileSocialAccountsResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj RefreshProfileSocialAccountsResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingUpdateSocialAccountsResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateSocialAccountsResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled UpdateSocialAccountsResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj UpdateSocialAccountsResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj UpdateSocialAccountsResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingUpdateTimezoneSocialAccountsResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &UpdateTimezoneSocialAccountsResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled UpdateTimezoneSocialAccountsResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj UpdateTimezoneSocialAccountsResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj UpdateTimezoneSocialAccountsResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringDeleteSocialAccountsResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &DeleteSocialAccountsResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeleteSocialAccountsResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringListSocialAccountsResponseItem(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &ListSocialAccountsResponseItem{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListSocialAccountsResponseItem
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringRefreshProfileSocialAccountsResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &RefreshProfileSocialAccountsResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RefreshProfileSocialAccountsResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringUpdateSocialAccountsResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &UpdateSocialAccountsResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdateSocialAccountsResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringUpdateTimezoneSocialAccountsResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &UpdateTimezoneSocialAccountsResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdateTimezoneSocialAccountsResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumListSocialAccountsResponseItemPlatform(t *testing.T) {
	t.Run("NewFromString_bluesky", func(t *testing.T) {
		t.Parallel()
		val, err := NewListSocialAccountsResponseItemPlatformFromString("bluesky")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ListSocialAccountsResponseItemPlatform("bluesky"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_facebook", func(t *testing.T) {
		t.Parallel()
		val, err := NewListSocialAccountsResponseItemPlatformFromString("facebook")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ListSocialAccountsResponseItemPlatform("facebook"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_instagram", func(t *testing.T) {
		t.Parallel()
		val, err := NewListSocialAccountsResponseItemPlatformFromString("instagram")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ListSocialAccountsResponseItemPlatform("instagram"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_linkedin", func(t *testing.T) {
		t.Parallel()
		val, err := NewListSocialAccountsResponseItemPlatformFromString("linkedin")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ListSocialAccountsResponseItemPlatform("linkedin"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_pinterest", func(t *testing.T) {
		t.Parallel()
		val, err := NewListSocialAccountsResponseItemPlatformFromString("pinterest")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ListSocialAccountsResponseItemPlatform("pinterest"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_threads", func(t *testing.T) {
		t.Parallel()
		val, err := NewListSocialAccountsResponseItemPlatformFromString("threads")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ListSocialAccountsResponseItemPlatform("threads"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_tiktok", func(t *testing.T) {
		t.Parallel()
		val, err := NewListSocialAccountsResponseItemPlatformFromString("tiktok")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ListSocialAccountsResponseItemPlatform("tiktok"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_twitter", func(t *testing.T) {
		t.Parallel()
		val, err := NewListSocialAccountsResponseItemPlatformFromString("twitter")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ListSocialAccountsResponseItemPlatform("twitter"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_youtube", func(t *testing.T) {
		t.Parallel()
		val, err := NewListSocialAccountsResponseItemPlatformFromString("youtube")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ListSocialAccountsResponseItemPlatform("youtube"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewListSocialAccountsResponseItemPlatformFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewListSocialAccountsResponseItemPlatformFromString("bluesky")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumListSocialAccountsResponseItemStatus(t *testing.T) {
	t.Run("NewFromString_connected", func(t *testing.T) {
		t.Parallel()
		val, err := NewListSocialAccountsResponseItemStatusFromString("connected")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ListSocialAccountsResponseItemStatus("connected"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_disconnected", func(t *testing.T) {
		t.Parallel()
		val, err := NewListSocialAccountsResponseItemStatusFromString("disconnected")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, ListSocialAccountsResponseItemStatus("disconnected"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewListSocialAccountsResponseItemStatusFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewListSocialAccountsResponseItemStatusFromString("connected")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumUpdateSocialAccountsRequestImageProcessingStatus(t *testing.T) {
	t.Run("NewFromString_PENDING", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateSocialAccountsRequestImageProcessingStatusFromString("PENDING")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateSocialAccountsRequestImageProcessingStatus("PENDING"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_PROCESSING", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateSocialAccountsRequestImageProcessingStatusFromString("PROCESSING")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateSocialAccountsRequestImageProcessingStatus("PROCESSING"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_PROCESSED", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateSocialAccountsRequestImageProcessingStatusFromString("PROCESSED")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateSocialAccountsRequestImageProcessingStatus("PROCESSED"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_FAILED", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateSocialAccountsRequestImageProcessingStatusFromString("FAILED")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateSocialAccountsRequestImageProcessingStatus("FAILED"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewUpdateSocialAccountsRequestImageProcessingStatusFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewUpdateSocialAccountsRequestImageProcessingStatusFromString("PENDING")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumUpdateSocialAccountsRequestPlatform(t *testing.T) {
	t.Run("NewFromString_bluesky", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateSocialAccountsRequestPlatformFromString("bluesky")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateSocialAccountsRequestPlatform("bluesky"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_facebook", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateSocialAccountsRequestPlatformFromString("facebook")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateSocialAccountsRequestPlatform("facebook"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_instagram", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateSocialAccountsRequestPlatformFromString("instagram")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateSocialAccountsRequestPlatform("instagram"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_linkedin", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateSocialAccountsRequestPlatformFromString("linkedin")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateSocialAccountsRequestPlatform("linkedin"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_pinterest", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateSocialAccountsRequestPlatformFromString("pinterest")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateSocialAccountsRequestPlatform("pinterest"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_threads", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateSocialAccountsRequestPlatformFromString("threads")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateSocialAccountsRequestPlatform("threads"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_tiktok", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateSocialAccountsRequestPlatformFromString("tiktok")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateSocialAccountsRequestPlatform("tiktok"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_twitter", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateSocialAccountsRequestPlatformFromString("twitter")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateSocialAccountsRequestPlatform("twitter"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_youtube", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateSocialAccountsRequestPlatformFromString("youtube")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateSocialAccountsRequestPlatform("youtube"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewUpdateSocialAccountsRequestPlatformFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewUpdateSocialAccountsRequestPlatformFromString("bluesky")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumUpdateSocialAccountsRequestStatus(t *testing.T) {
	t.Run("NewFromString_connected", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateSocialAccountsRequestStatusFromString("connected")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateSocialAccountsRequestStatus("connected"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_disconnected", func(t *testing.T) {
		t.Parallel()
		val, err := NewUpdateSocialAccountsRequestStatusFromString("disconnected")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, UpdateSocialAccountsRequestStatus("disconnected"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewUpdateSocialAccountsRequestStatusFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewUpdateSocialAccountsRequestStatusFromString("connected")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesDeleteSocialAccountsResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &DeleteSocialAccountsResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeleteSocialAccountsResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesListSocialAccountsResponseItem(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &ListSocialAccountsResponseItem{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *ListSocialAccountsResponseItem
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesRefreshProfileSocialAccountsResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &RefreshProfileSocialAccountsResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *RefreshProfileSocialAccountsResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesUpdateSocialAccountsResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &UpdateSocialAccountsResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdateSocialAccountsResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesUpdateTimezoneSocialAccountsResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &UpdateTimezoneSocialAccountsResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *UpdateTimezoneSocialAccountsResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
