// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/schedulin-app/schedulin-go/internal"
	big "math/big"
)

var (
	createWebhooksRequestFieldURL         = big.NewInt(1 << 0)
	createWebhooksRequestFieldEvents      = big.NewInt(1 << 1)
	createWebhooksRequestFieldDescription = big.NewInt(1 << 2)
)

type CreateWebhooksRequest struct {
	URL         string                            `json:"url" url:"-"`
	Events      []CreateWebhooksRequestEventsItem `json:"events" url:"-"`
	Description *string                           `json:"description,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateWebhooksRequest) require(field *big.Int) {
	next := new(big.Int)
	if c.explicitFields != nil {
		next.Set(c.explicitFields)
	}
	next.Or(next, field)
	c.explicitFields = next
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateWebhooksRequest) SetURL(url string) {
	c.URL = url
	c.require(createWebhooksRequestFieldURL)
}

// SetEvents sets the Events field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateWebhooksRequest) SetEvents(events []CreateWebhooksRequestEventsItem) {
	c.Events = events
	c.require(createWebhooksRequestFieldEvents)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateWebhooksRequest) SetDescription(description *string) {
	c.Description = description
	c.require(createWebhooksRequestFieldDescription)
}

func (c *CreateWebhooksRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateWebhooksRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateWebhooksRequest(body)
	return nil
}

func (c *CreateWebhooksRequest) MarshalJSON() ([]byte, error) {
	type embed CreateWebhooksRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteWebhooksRequestFieldID = big.NewInt(1 << 0)
)

type DeleteWebhooksRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteWebhooksRequest) require(field *big.Int) {
	next := new(big.Int)
	if d.explicitFields != nil {
		next.Set(d.explicitFields)
	}
	next.Or(next, field)
	d.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteWebhooksRequest) SetID(id string) {
	d.ID = id
	d.require(deleteWebhooksRequestFieldID)
}

func (d *DeleteWebhooksRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteWebhooksRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*d = DeleteWebhooksRequest(body)
	return nil
}

func (d *DeleteWebhooksRequest) MarshalJSON() ([]byte, error) {
	type embed DeleteWebhooksRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	listDeliveriesWebhooksRequestFieldID    = big.NewInt(1 << 0)
	listDeliveriesWebhooksRequestFieldLimit = big.NewInt(1 << 1)
	listDeliveriesWebhooksRequestFieldPage  = big.NewInt(1 << 2)
)

type ListDeliveriesWebhooksRequest struct {
	ID    string `json:"-" url:"-"`
	Limit *int   `json:"-" url:"limit,omitempty"`
	Page  *int   `json:"-" url:"page,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListDeliveriesWebhooksRequest) require(field *big.Int) {
	next := new(big.Int)
	if l.explicitFields != nil {
		next.Set(l.explicitFields)
	}
	next.Or(next, field)
	l.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDeliveriesWebhooksRequest) SetID(id string) {
	l.ID = id
	l.require(listDeliveriesWebhooksRequestFieldID)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDeliveriesWebhooksRequest) SetLimit(limit *int) {
	l.Limit = limit
	l.require(listDeliveriesWebhooksRequestFieldLimit)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListDeliveriesWebhooksRequest) SetPage(page *int) {
	l.Page = page
	l.require(listDeliveriesWebhooksRequestFieldPage)
}

var (
	retrieveWebhooksRequestFieldID = big.NewInt(1 << 0)
)

type RetrieveWebhooksRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RetrieveWebhooksRequest) require(field *big.Int) {
	next := new(big.Int)
	if r.explicitFields != nil {
		next.Set(r.explicitFields)
	}
	next.Or(next, field)
	r.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveWebhooksRequest) SetID(id string) {
	r.ID = id
	r.require(retrieveWebhooksRequestFieldID)
}

var (
	rotateSecretWebhooksRequestFieldID = big.NewInt(1 << 0)
)

type RotateSecretWebhooksRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RotateSecretWebhooksRequest) require(field *big.Int) {
	next := new(big.Int)
	if r.explicitFields != nil {
		next.Set(r.explicitFields)
	}
	next.Or(next, field)
	r.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RotateSecretWebhooksRequest) SetID(id string) {
	r.ID = id
	r.require(rotateSecretWebhooksRequestFieldID)
}

func (r *RotateSecretWebhooksRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler RotateSecretWebhooksRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = RotateSecretWebhooksRequest(body)
	return nil
}

func (r *RotateSecretWebhooksRequest) MarshalJSON() ([]byte, error) {
	type embed RotateSecretWebhooksRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	testWebhooksRequestFieldID = big.NewInt(1 << 0)
)

type TestWebhooksRequest struct {
	ID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (t *TestWebhooksRequest) require(field *big.Int) {
	next := new(big.Int)
	if t.explicitFields != nil {
		next.Set(t.explicitFields)
	}
	next.Or(next, field)
	t.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TestWebhooksRequest) SetID(id string) {
	t.ID = id
	t.require(testWebhooksRequestFieldID)
}

func (t *TestWebhooksRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler TestWebhooksRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*t = TestWebhooksRequest(body)
	return nil
}

func (t *TestWebhooksRequest) MarshalJSON() ([]byte, error) {
	type embed TestWebhooksRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

type CreateWebhooksRequestEventsItem string

const (
	CreateWebhooksRequestEventsItemPostPublished       CreateWebhooksRequestEventsItem = "post.published"
	CreateWebhooksRequestEventsItemPostFailed          CreateWebhooksRequestEventsItem = "post.failed"
	CreateWebhooksRequestEventsItemGenerationCompleted CreateWebhooksRequestEventsItem = "generation.completed"
	CreateWebhooksRequestEventsItemGenerationFailed    CreateWebhooksRequestEventsItem = "generation.failed"
)

func NewCreateWebhooksRequestEventsItemFromString(s string) (CreateWebhooksRequestEventsItem, error) {
	switch s {
	case "post.published":
		return CreateWebhooksRequestEventsItemPostPublished, nil
	case "post.failed":
		return CreateWebhooksRequestEventsItemPostFailed, nil
	case "generation.completed":
		return CreateWebhooksRequestEventsItemGenerationCompleted, nil
	case "generation.failed":
		return CreateWebhooksRequestEventsItemGenerationFailed, nil
	}
	var t CreateWebhooksRequestEventsItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateWebhooksRequestEventsItem) Ptr() *CreateWebhooksRequestEventsItem {
	return &c
}

type UpdateWebhooksRequestEventsItem string

const (
	UpdateWebhooksRequestEventsItemPostPublished       UpdateWebhooksRequestEventsItem = "post.published"
	UpdateWebhooksRequestEventsItemPostFailed          UpdateWebhooksRequestEventsItem = "post.failed"
	UpdateWebhooksRequestEventsItemGenerationCompleted UpdateWebhooksRequestEventsItem = "generation.completed"
	UpdateWebhooksRequestEventsItemGenerationFailed    UpdateWebhooksRequestEventsItem = "generation.failed"
)

func NewUpdateWebhooksRequestEventsItemFromString(s string) (UpdateWebhooksRequestEventsItem, error) {
	switch s {
	case "post.published":
		return UpdateWebhooksRequestEventsItemPostPublished, nil
	case "post.failed":
		return UpdateWebhooksRequestEventsItemPostFailed, nil
	case "generation.completed":
		return UpdateWebhooksRequestEventsItemGenerationCompleted, nil
	case "generation.failed":
		return UpdateWebhooksRequestEventsItemGenerationFailed, nil
	}
	var t UpdateWebhooksRequestEventsItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateWebhooksRequestEventsItem) Ptr() *UpdateWebhooksRequestEventsItem {
	return &u
}

var (
	updateWebhooksRequestFieldID          = big.NewInt(1 << 0)
	updateWebhooksRequestFieldURL         = big.NewInt(1 << 1)
	updateWebhooksRequestFieldEvents      = big.NewInt(1 << 2)
	updateWebhooksRequestFieldDescription = big.NewInt(1 << 3)
	updateWebhooksRequestFieldEnabled     = big.NewInt(1 << 4)
)

type UpdateWebhooksRequest struct {
	ID          string                            `json:"-" url:"-"`
	URL         *string                           `json:"url,omitempty" url:"-"`
	Events      []UpdateWebhooksRequestEventsItem `json:"events,omitempty" url:"-"`
	Description *string                           `json:"description,omitempty" url:"-"`
	Enabled     *bool                             `json:"enabled,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateWebhooksRequest) require(field *big.Int) {
	next := new(big.Int)
	if u.explicitFields != nil {
		next.Set(u.explicitFields)
	}
	next.Or(next, field)
	u.explicitFields = next
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateWebhooksRequest) SetID(id string) {
	u.ID = id
	u.require(updateWebhooksRequestFieldID)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateWebhooksRequest) SetURL(url *string) {
	u.URL = url
	u.require(updateWebhooksRequestFieldURL)
}

// SetEvents sets the Events field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateWebhooksRequest) SetEvents(events []UpdateWebhooksRequestEventsItem) {
	u.Events = events
	u.require(updateWebhooksRequestFieldEvents)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateWebhooksRequest) SetDescription(description *string) {
	u.Description = description
	u.require(updateWebhooksRequestFieldDescription)
}

// SetEnabled sets the Enabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateWebhooksRequest) SetEnabled(enabled *bool) {
	u.Enabled = enabled
	u.require(updateWebhooksRequestFieldEnabled)
}

func (u *UpdateWebhooksRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateWebhooksRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateWebhooksRequest(body)
	return nil
}

func (u *UpdateWebhooksRequest) MarshalJSON() ([]byte, error) {
	type embed UpdateWebhooksRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
