// Code generated by Fern. DO NOT EDIT.

package posts

import (
	context "context"

	schedulingo "github.com/schedulin-app/schedulin-go"
	core "github.com/schedulin-app/schedulin-go/core"
	internal "github.com/schedulin-app/schedulin-go/internal"
	option "github.com/schedulin-app/schedulin-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Search and filter posts with various criteria including status, date range, social accounts, and tags
//
// Example:
//
//	request := &schedulingo.ListPostsRequest{}
//	client.Posts.List(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) List(
	ctx context.Context,
	request *schedulingo.ListPostsRequest,
	opts ...option.RequestOption,
) (*schedulingo.ListPostsResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a new post with media, tags, and scheduling options. Media items may reference a stored library URL or any publicly reachable image/video URL — external URLs are downloaded into the media library automatically, so clients that cannot issue a raw presigned PUT can attach media in one call.
//
// Example:
//
//	request := &schedulingo.PostCreate{
//	    Caption: "caption",
//	    SocialAccountID: "socialAccountId",
//	}
//	client.Posts.Create(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Create(
	ctx context.Context,
	request *schedulingo.PostCreate,
	opts ...option.RequestOption,
) (*schedulingo.CreatePostsResponse, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns counts of posts for the Queue, Drafts, Approvals, and Sent tabs
//
// Example:
//
//	request := &schedulingo.CountByTabPostsRequest{}
//	client.Posts.CountByTab(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) CountByTab(
	ctx context.Context,
	request *schedulingo.CountByTabPostsRequest,
	opts ...option.RequestOption,
) (*schedulingo.CountByTabPostsResponse, error) {
	response, err := c.WithRawResponse.CountByTab(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve a single post by its ID with all relations
//
// Example:
//
//	request := &schedulingo.RetrievePostsRequest{
//	    ID: "id",
//	}
//	client.Posts.Retrieve(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Retrieve(
	ctx context.Context,
	request *schedulingo.RetrievePostsRequest,
	opts ...option.RequestOption,
) (*schedulingo.PostWithRelations, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update an existing draft or scheduled post by its ID. `status` may be DRAFT, SCHEDULED (requires a future `scheduledAt`, either in this request or already on the post), or PROCESSING (publish now). COMPLETED and FAILED are set only by the publisher. Posts that are already publishing, published, or failed can't be edited (409).
//
// Example:
//
//	request := &schedulingo.UpdatePostsRequest{
//	    ID: "id",
//	}
//	client.Posts.Update(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Update(
	ctx context.Context,
	request *schedulingo.UpdatePostsRequest,
	opts ...option.RequestOption,
) (*schedulingo.Post, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a post by its ID
//
// Example:
//
//	request := &schedulingo.DeletePostsRequest{
//	    ID: "id",
//	}
//	client.Posts.Delete(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Delete(
	ctx context.Context,
	request *schedulingo.DeletePostsRequest,
	opts ...option.RequestOption,
) (*schedulingo.Post, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the latest analytics snapshot for a post
//
// Example:
//
//	request := &schedulingo.AnalyticsSummaryPostsRequest{
//	    ID: "id",
//	}
//	client.Posts.AnalyticsSummary(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) AnalyticsSummary(
	ctx context.Context,
	request *schedulingo.AnalyticsSummaryPostsRequest,
	opts ...option.RequestOption,
) (*schedulingo.AnalyticsSummaryPostsResponse, error) {
	response, err := c.WithRawResponse.AnalyticsSummary(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve time series analytics metrics for a post
//
// Example:
//
//	request := &schedulingo.AnalyticsSeriesPostsRequest{
//	    ID: "id",
//	}
//	client.Posts.AnalyticsSeries(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) AnalyticsSeries(
	ctx context.Context,
	request *schedulingo.AnalyticsSeriesPostsRequest,
	opts ...option.RequestOption,
) (*schedulingo.AnalyticsSeriesPostsResponse, error) {
	response, err := c.WithRawResponse.AnalyticsSeries(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Publish a draft post to connected social media accounts
//
// Example:
//
//	request := &schedulingo.PublishDraftPostsRequest{
//	    ID: "id",
//	}
//	client.Posts.PublishDraft(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) PublishDraft(
	ctx context.Context,
	request *schedulingo.PublishDraftPostsRequest,
	opts ...option.RequestOption,
) (*schedulingo.Post, error) {
	response, err := c.WithRawResponse.PublishDraft(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Replace all tags on a post. No status restrictions apply.
//
// Example:
//
//	request := &schedulingo.UpdateTagsPostsRequest{
//	    ID: "id",
//	    TagIDs: []string{
//	        "tagIds",
//	    },
//	}
//	client.Posts.UpdateTags(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) UpdateTags(
	ctx context.Context,
	request *schedulingo.UpdateTagsPostsRequest,
	opts ...option.RequestOption,
) (*schedulingo.Post, error) {
	response, err := c.WithRawResponse.UpdateTags(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
