// Code generated by Fern. DO NOT EDIT.

package socialaccounts

import (
	context "context"
	http "net/http"

	schedulingo "github.com/schedulin-app/schedulin-go"
	core "github.com/schedulin-app/schedulin-go/core"
	internal "github.com/schedulin-app/schedulin-go/internal"
	option "github.com/schedulin-app/schedulin-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) List(
	ctx context.Context,
	opts ...option.RequestOption,
) (*core.Response[*schedulingo.ListSocialAccountsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.schedulin.app",
	)
	endpointURL := baseURL + "/v0/social-accounts"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *schedulingo.ListSocialAccountsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(schedulingo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*schedulingo.ListSocialAccountsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Update(
	ctx context.Context,
	request *schedulingo.UpdateSocialAccountsRequest,
	opts ...option.RequestOption,
) (*core.Response[*schedulingo.UpdateSocialAccountsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.schedulin.app",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v0/social-accounts/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *schedulingo.UpdateSocialAccountsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPut,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(schedulingo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*schedulingo.UpdateSocialAccountsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Delete(
	ctx context.Context,
	request *schedulingo.DeleteSocialAccountsRequest,
	opts ...option.RequestOption,
) (*core.Response[*schedulingo.DeleteSocialAccountsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.schedulin.app",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v0/social-accounts/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *schedulingo.DeleteSocialAccountsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(schedulingo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*schedulingo.DeleteSocialAccountsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) UpdateTimezone(
	ctx context.Context,
	request *schedulingo.UpdateTimezoneSocialAccountsRequest,
	opts ...option.RequestOption,
) (*core.Response[*schedulingo.UpdateTimezoneSocialAccountsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.schedulin.app",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v0/social-accounts/%v/timezone",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *schedulingo.UpdateTimezoneSocialAccountsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPut,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(schedulingo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*schedulingo.UpdateTimezoneSocialAccountsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) PinterestBoards(
	ctx context.Context,
	request *schedulingo.PinterestBoardsSocialAccountsRequest,
	opts ...option.RequestOption,
) (*core.Response[*schedulingo.PinterestBoardsSocialAccountsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.schedulin.app",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v0/social-accounts/%v/pinterest-boards",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *schedulingo.PinterestBoardsSocialAccountsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(schedulingo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*schedulingo.PinterestBoardsSocialAccountsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) TiktokCreatorInfo(
	ctx context.Context,
	request *schedulingo.TiktokCreatorInfoSocialAccountsRequest,
	opts ...option.RequestOption,
) (*core.Response[*schedulingo.TiktokCreatorInfoSocialAccountsResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.schedulin.app",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v0/social-accounts/%v/tiktok-creator-info",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *schedulingo.TiktokCreatorInfoSocialAccountsResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(schedulingo.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*schedulingo.TiktokCreatorInfoSocialAccountsResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
