// Code generated by Fern. DO NOT EDIT.

package tags

import (
	context "context"

	schedulingo "github.com/schedulin/schedulin-go"
	core "github.com/schedulin/schedulin-go/core"
	internal "github.com/schedulin/schedulin-go/internal"
	option "github.com/schedulin/schedulin-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Retrieve a list of tags for the authenticated user with optional search filtering
func (c *Client) List(
	ctx context.Context,
	request *schedulingo.ListTagsRequest,
	opts ...option.RequestOption,
) ([]*schedulingo.Tag, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a new tag. Users can have up to 5 tags.
func (c *Client) Create(
	ctx context.Context,
	request *schedulingo.CreateTagsRequest,
	opts ...option.RequestOption,
) (*schedulingo.Tag, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update an existing tag by its ID. Only the tag owner can update their tags.
func (c *Client) Update(
	ctx context.Context,
	request *schedulingo.UpdateTagsRequest,
	opts ...option.RequestOption,
) (*schedulingo.Tag, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a tag by its ID. Only the tag owner can delete their tags.
func (c *Client) Delete(
	ctx context.Context,
	request *schedulingo.DeleteTagsRequest,
	opts ...option.RequestOption,
) (*schedulingo.Tag, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
