// Code generated by Fern. DO NOT EDIT.

package webhooks

import (
	context "context"

	schedulin "github.com/schedulin-app/schedulin-go"
	core "github.com/schedulin-app/schedulin-go/core"
	internal "github.com/schedulin-app/schedulin-go/internal"
	option "github.com/schedulin-app/schedulin-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// List the organization's webhook endpoints. Signing secrets are masked.
//
// Example:
//
//	client.Webhooks.List(
//	    context.TODO(),
//	)
func (c *Client) List(
	ctx context.Context,
	opts ...option.RequestOption,
) (*schedulin.ListWebhooksResponse, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Register an HTTPS endpoint for event deliveries. The response includes the signing secret ONCE — store it; later reads return a masked value.
//
// Example:
//
//	request := &schedulin.CreateWebhooksRequest{
//	    URL: "url",
//	    Events: []schedulin.CreateWebhooksRequestEventsItem{
//	        schedulin.CreateWebhooksRequestEventsItemPostPublished,
//	    },
//	}
//	client.Webhooks.Create(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Create(
	ctx context.Context,
	request *schedulin.CreateWebhooksRequest,
	opts ...option.RequestOption,
) (*schedulin.WebhookEndpoint, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve one webhook endpoint, including failure counters. The signing secret is masked.
//
// Example:
//
//	request := &schedulin.RetrieveWebhooksRequest{
//	    ID: "id",
//	}
//	client.Webhooks.Retrieve(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Retrieve(
	ctx context.Context,
	request *schedulin.RetrieveWebhooksRequest,
	opts ...option.RequestOption,
) (*schedulin.WebhookEndpoint, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete a webhook endpoint and its delivery history. Deliveries already in flight are dropped.
//
// Example:
//
//	request := &schedulin.DeleteWebhooksRequest{
//	    ID: "id",
//	}
//	client.Webhooks.Delete(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Delete(
	ctx context.Context,
	request *schedulin.DeleteWebhooksRequest,
	opts ...option.RequestOption,
) (*schedulin.DeleteWebhooksResponse, error) {
	response, err := c.WithRawResponse.Delete(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update URL, subscribed events, description, or enabled state. Re-enabling resets the failure streak.
//
// Example:
//
//	request := &schedulin.UpdateWebhooksRequest{
//	    ID: "id",
//	}
//	client.Webhooks.Update(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Update(
	ctx context.Context,
	request *schedulin.UpdateWebhooksRequest,
	opts ...option.RequestOption,
) (*schedulin.WebhookEndpoint, error) {
	response, err := c.WithRawResponse.Update(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Generate a new signing secret for the endpoint and return it ONCE. The old secret stops signing immediately.
//
// Example:
//
//	request := &schedulin.RotateSecretWebhooksRequest{
//	    ID: "id",
//	}
//	client.Webhooks.RotateSecret(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) RotateSecret(
	ctx context.Context,
	request *schedulin.RotateSecretWebhooksRequest,
	opts ...option.RequestOption,
) (*schedulin.WebhookEndpoint, error) {
	response, err := c.WithRawResponse.RotateSecret(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Send a signed `ping` event to the endpoint URL and record it in the delivery history.
//
// Example:
//
//	request := &schedulin.TestWebhooksRequest{
//	    ID: "id",
//	}
//	client.Webhooks.Test(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Test(
	ctx context.Context,
	request *schedulin.TestWebhooksRequest,
	opts ...option.RequestOption,
) (*schedulin.TestWebhooksResponse, error) {
	response, err := c.WithRawResponse.Test(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delivery history for a webhook endpoint: event, status, attempts, last response code, and payload.
//
// Example:
//
//	request := &schedulin.ListDeliveriesWebhooksRequest{
//	    ID: "id",
//	}
//	client.Webhooks.ListDeliveries(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ListDeliveries(
	ctx context.Context,
	request *schedulin.ListDeliveriesWebhooksRequest,
	opts ...option.RequestOption,
) (*schedulin.ListDeliveriesWebhooksResponse, error) {
	response, err := c.WithRawResponse.ListDeliveries(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
