// Code generated by Fern. DO NOT EDIT.

package webhooks

import (
	context "context"
	http "net/http"

	schedulin "github.com/schedulin-app/schedulin-go"
	core "github.com/schedulin-app/schedulin-go/core"
	internal "github.com/schedulin-app/schedulin-go/internal"
	option "github.com/schedulin-app/schedulin-go/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) List(
	ctx context.Context,
	opts ...option.RequestOption,
) (*core.Response[*schedulin.ListWebhooksResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.schedulin.app",
	)
	endpointURL := baseURL + "/v0/webhooks"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *schedulin.ListWebhooksResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(schedulin.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*schedulin.ListWebhooksResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Create(
	ctx context.Context,
	request *schedulin.CreateWebhooksRequest,
	opts ...option.RequestOption,
) (*core.Response[*schedulin.WebhookEndpoint], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.schedulin.app",
	)
	endpointURL := baseURL + "/v0/webhooks"
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *schedulin.WebhookEndpoint
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(schedulin.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*schedulin.WebhookEndpoint]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Retrieve(
	ctx context.Context,
	request *schedulin.RetrieveWebhooksRequest,
	opts ...option.RequestOption,
) (*core.Response[*schedulin.WebhookEndpoint], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.schedulin.app",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v0/webhooks/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *schedulin.WebhookEndpoint
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(schedulin.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*schedulin.WebhookEndpoint]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Delete(
	ctx context.Context,
	request *schedulin.DeleteWebhooksRequest,
	opts ...option.RequestOption,
) (*core.Response[*schedulin.DeleteWebhooksResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.schedulin.app",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v0/webhooks/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *schedulin.DeleteWebhooksResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(schedulin.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*schedulin.DeleteWebhooksResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Update(
	ctx context.Context,
	request *schedulin.UpdateWebhooksRequest,
	opts ...option.RequestOption,
) (*core.Response[*schedulin.WebhookEndpoint], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.schedulin.app",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v0/webhooks/%v",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *schedulin.WebhookEndpoint
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPatch,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(schedulin.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*schedulin.WebhookEndpoint]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) RotateSecret(
	ctx context.Context,
	request *schedulin.RotateSecretWebhooksRequest,
	opts ...option.RequestOption,
) (*core.Response[*schedulin.WebhookEndpoint], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.schedulin.app",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v0/webhooks/%v/rotate-secret",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *schedulin.WebhookEndpoint
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(schedulin.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*schedulin.WebhookEndpoint]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Test(
	ctx context.Context,
	request *schedulin.TestWebhooksRequest,
	opts ...option.RequestOption,
) (*core.Response[*schedulin.TestWebhooksResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.schedulin.app",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v0/webhooks/%v/test",
		request.ID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	headers.Add("Content-Type", "application/json")
	var response *schedulin.TestWebhooksResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(schedulin.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*schedulin.TestWebhooksResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) ListDeliveries(
	ctx context.Context,
	request *schedulin.ListDeliveriesWebhooksRequest,
	opts ...option.RequestOption,
) (*core.Response[*schedulin.ListDeliveriesWebhooksResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api.schedulin.app",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/v0/webhooks/%v/deliveries",
		request.ID,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *schedulin.ListDeliveriesWebhooksResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(schedulin.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*schedulin.ListDeliveriesWebhooksResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
